# Generated by Django 4.2 on 2024-03-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQK_eMYVFak3g9jCIWLUCPq-8jbWCq6aPxc0i-OJFTIBg&s', max_length=600),
        ),
    ]
